### ISSUE TITLE
Authors.md file already exists

### ISSUE THREAD

**Issue by CaidenKehrer** [mysticmind/mysticmind-postgresembed#19]
Some Extensions replace the authors.md file, This causes a crash when attempting to add the extension. 

Example: 
https://download.osgeo.org/postgis/windows/pg96/postgis-bundle-pg96-3.2.3x64.zip
This zip file creates the authors.md file. However, since it already exists from psql it causes an exception.

**Comment by mysticmind** [comment]
Thanks for reporting this, will address it in the upcoming release 2.0.0

**Comment by mysticmind** [comment]
2.0.0 released with a fix for this issue.
