### ISSUE TITLE
dotnet6 compatibility issue

### ISSUE THREAD

**Issue by himenkumars** [mysticmind/mysticmind-postgresembed#20]
Hi, Upgraded my solution to .NET6 , It was NET Core 2.1 earlier.
I see after upgrade, There some unit test are getting failed due to assertion, it looks like database operation are skipped.
This is very old project, and I am not aware about much functionality.

Can you confirm , that this package is compatible with dotnet6 ?

**Comment by mysticmind** [comment]
It is not tested in dotnet6. By next week or so, will test on dotnet6 and do any fixes required.

**Comment by mysticmind** [comment]
Also can you elaborate what errors are you getting?

**Comment by himenkumars** [comment]
Thanks for quick reply.

There is no error/exception on build. Some Unit test get passed also. 
but some gets failed on assertion due to expected data mismatch, 
that suppose to get updated in embeded database. but it is not updated.
I wont be able to give more detail.

**Comment by himenkumars** [comment]
Hi @mysticmind ,
Hope you have nice weekend.
Did you get a chance to look into this for dotnet6 compatibility?

**Comment by mysticmind** [comment]
PR https://github.com/mysticmind/mysticmind-postgresembed/pull/21 - Await for 2.0.0 which specifically targets .NET 6. I will release it later today.

As such there are no issues with the .NET target but if you are seeing failures with `initdb` then it is a dependency issue for Postgres itself, you would need to install [Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784).

Also check the [readme known issues section](https://github.com/mysticmind/mysticmind-postgresembed#known-issues).

**Comment by mysticmind** [comment]
Resolved via GH-21

**Comment by mysticmind** [comment]
2.0.0 released which targets `net6.0`
