### ISSUE TITLE
Which version to pick?

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [mysticmind/mysticmind-postgresembed#25]
As the default https://github.com/mihasic/PostgreSql.Binaries.Lite is now archieved and not longer maintained, how can i change to another version?

How can i change the version search? the binaries stop at around 9.5.5.1 which is a too old version of postgres

**Comment by mysticmind** [comment]
I will have an alternate mechanism in a week or so, will keep you posted.

**Comment by IXLLEGACYIXL** [comment]
thank you very much

**Comment by mysticmind** [comment]
Fixed via https://github.com/mysticmind/mysticmind-postgresembed/commit/2c8fdefaa2e983196e01c6ff334eaa881839a779. 3.0.0 will be released soon. There are few breaking changes etc. Lib now can run cross-platform and cross-architecture on Windows, OSX (Including Silicon) and Linux.

**Comment by mysticmind** [comment]
v3.0.0 is released to NuGet.
