### ISSUE TITLE
Unable to access a directory due to use by another process

### ISSUE THREAD

**Issue by SeanFarrow** [mysticmind/mysticmind-postgresembed#3]
Whilst using the library and setting the options to remove all directories, I get an error stating that the directories could not be removed due to being used by another process.

Should we look at using a Polly Retry policy to solve this problem and backing off exponentially until the directory(s) could be removed or a specified number of retries has been reached handling any exceptions in the process?

I'm happyto do the work if required as it's something I need reasonably quickly.

**Comment by mysticmind** [comment]
@SeanFarrow Sure, go ahead and implement it, I am happy to take a PR.

**Comment by mysticmind** [comment]
Fixed via PR #5
