### ISSUE TITLE
InitDb crashes due to empty locale

### ISSUE THREAD

**Issue by erikljung** [mysticmind/mysticmind-postgresembed#7]
Hi, I've built a small tool based on your project, everything works fine (thank you). We have one small issue where people with different OS/locale settings gets different or no locale when initdb.exe is executed. In the no locale case the server cannot be started -- resulting in the error below.
I've created a pull request which I hope you will consider.

System.Exception
  HResult=0x80131500
  Message=Error occurred while executing InitDb
  Source=MysticMind.PostgresEmbed
  StackTrace:
   at MysticMind.PostgresEmbed.PgServer.InitDb()
   at MysticMind.PostgresEmbed.PgServer.Start()
   ......

Inner Exception 1:
Exception: InitDb execution returned an error code The files belonging to this database system will be owned by user "PM".This user must also own the server process.The database cluster will be initialized with locale "".initdb: could not find suitable text search configuration for locale ""The default text search configuration will be set to "simple".Data page checksums are disabled.fixing permissions on existing directory ./pg_embed/375132f1-5142-4695-b572-2e58bf7675b4/data ... okcreating subdirectories ... okselecting default max_connections ... 100selecting default shared_buffers ... 128MBselecting dynamic shared memory implementation ... windowscreating configuration files ... okrunning bootstrap script ...

**Comment by mysticmind** [comment]
Fixed via #8
